---
title: "Midpoint Deliverable"
author: "John Boyle, Nhat Trang, Joseph Oh, Jason Tsai"
date: "5/21/2020"
output: html_document
---

```{r setup, include=FALSE}
source("scripts/sumInfo.R")
source("scripts/sumTable.R")
source("chart1.R")
source("chart2.R")
```

## COVID-19 Data Analysis

Our domain of interest is the recent outbreak of coronavirus. With this dataset, we analyzed how COVID-19 has impacted countries around the world. This dataset specifically analyzes the frequency of people's inhabitation of common areas including workplaces, parks, or transit stations over the time of February 23rd, to April 5th, when the most critical amount of outbreak occured.

## Quick Data

The country that had the most cases during this timeframe was **`r most_cases_country[1]`** with **`r most_cases_country[2]`** cases. In **`r most_cases_country[1]`**, the frequency of park visitors on average changed **`r most_cases_country$park_avg`** percent each consecutive day in this period. The country least impacted by the pandemic in this timeframe is **`r least_cases_country[1]`**, with **`r least_cases_country[2]`** cases. In **`r least_cases_country[1]`**, the frequency of park visitors on average changed **`r least_cases_country$park_avg`** percent each consecutive day in this period.

The country that had the most death during this timeframe was **`r most_death_country[1]`** with **`r most_death_country[2]`** casualities. In **`r most_death_country[1]`**, the frequency of park visitors on average changed **`r most_death_country$park_avg`** percent each consecutive day in this period. The country with the least amount of COVID-19 related deaths this timeframe is **`r least_death_country[1]`**, with **`r least_death_country[2]`** cases. In **`r least_death_country[1]`**, the frequency of park visitors on average changed **`r least_death_country$park_avg`** percent each consecutive day in this period.

## Plot of cases by country:

`r summary(data)`

This table shows the total deaths and cases of each country throughout the time period. This table allows to compare the statistics between the different countries.

## Data Chart
### **Chart1**
`r chart1(data)`

This chart will visualize the **gradual percentage change of people staying home after the outbreak of COVID-19.** The ups and downs will be within the timeframe from _Feb 23rd to April 5th of 2020._ The percent change was calculated each day.
Four countries, **US, Spain, Italy, and France,** are filtered from the dataset purposefully because the spread of the virus was most fatal to those countries.
This chart is included to find _correlation_ with another chart that depicts the total counts of confirmed cases increasing by each day. It will further help us to seek how change in community mobility and increasing number of confirmed cases are related.

### **Chart2**
`r chart2(data)`

This chart reveals the **trend of confirmed cases increasing by days** in four different country: **US, Spain, Italy, and France.** This chart was included to better seek the _correlation between mobility of citizens and the speed of the virus spreading within each country._ Each country shows different trends along with different rates of mobility which makes it easier to compare them and potentially find a pattern.
